name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify the latest .NET version

      - name: Install dependencies
        run: dotnet restore ./musicApp3/musicApp3.sln

      - name: Build
        run: dotnet build ./musicApp3/musicApp3.sln --configuration Release

      - name: Publish
        run: dotnet publish ./musicApp3/musicApp3.sln --configuration Release --output ./musicApp3/output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./musicApp3/output
