name: Build and Publish cs_music_player

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x' # Specify the .NET version used by cs_music_player

      - name: Install dependencies
        run: dotnet restore cs_music_player.sln

      - name: Build
        run: dotnet build cs_music_player.sln --configuration Release

      - name: Publish
        run: dotnet publish cs_music_player.sln --configuration Release --output ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cs_music_player_executable
          path: ./output
